version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - ../secrets/.env_file.sh
    restart: always

    ports:
       - "3306:3306"
    networks:
      - inception

  nginx:
    container_name: nginx
    env_file: 
      - ../secrets/.env_file.sh
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    networks:
      - inception 


  wordpress:
    container_name: wordpress
    env_file: 
      - ../secrets/.env_file.sh
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    networks:
      - inception 





  
networks:
  inception:
    driver: bridge
