services:

  mariadb:

    container_name: mariadb

    command: ["/bin/bash", "-c", "source ../secrets/.env_file.sh"]

    build: 
      context: requirements/mariadb/
      dockerfile: Dockerfile

    env_file:
      - ../secrets/.env_file.sh
    restart: always
    #image: mariadb:user
   
    ports:
       - "3306:3306"


  nginx:

    #image: nginx
    container_name: nginx

    env_file: 
      - ../secrets/.env_file.sh

    build:
      context: requirements/nginx/
      dockerfile: Dockerfile

    restart: always


    ports:
      - "443:443"

